# Generated by Django 3.0.3 on 2020-09-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teamer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('city', models.CharField(blank=True, choices=[('leipzig', 'Leipzig'), ('jena', 'Jena')], max_length=30, verbose_name='Stadt')),
                ('picture', models.ImageField(upload_to='team_pictures/', verbose_name='Foto')),
                ('name', models.CharField(default='Jon Doe', max_length=100, verbose_name='Name')),
                ('position', models.CharField(default='Trainer', max_length=100, verbose_name='Position')),
                ('notes', models.TextField(blank=True, verbose_name='Sonstiges')),
                ('public_telnr', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefonnummer')),
                ('public_email', models.CharField(blank=True, max_length=150, null=True, verbose_name='Email')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
    ]
