# Generated by Django 3.0.3 on 2021-04-23 12:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interested', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventMerch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('image', models.ImageField(upload_to='PublicEvents/Images/Merch', verbose_name='Artikelbild')),
                ('price', models.FloatField(verbose_name='Preis')),
                ('sizes', models.TextField(default='XS\tS\tM\tL\tXL\tXXL', verbose_name='Größen')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('description_rendered', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=300, verbose_name='Nachname')),
                ('birthday', models.DateTimeField(verbose_name='Geburtsdatum')),
                ('email', models.CharField(max_length=300, verbose_name='Emailadresse')),
                ('phone', models.CharField(max_length=30, verbose_name='Telefonnummer')),
                ('contact', models.CharField(max_length=200, verbose_name='Kontaktmöglichkeit')),
                ('payed', models.BooleanField(default=False, verbose_name='Bezahlt')),
            ],
        ),
        migrations.CreateModel(
            name='PublicEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Event-name')),
                ('slug', models.SlugField(unique=True)),
                ('header_picture', models.ImageField(upload_to='PublicEvents/Images/Headers', verbose_name='Veranstaltungsbild')),
                ('place', models.CharField(blank=True, default='Leipzig', max_length=200, verbose_name='Veranstaltungsort')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('description_rendered', models.TextField(blank=True, null=True)),
                ('deadline', models.DateTimeField(default=datetime.datetime(2020, 11, 14, 1, 54, 52, 799289), verbose_name='Anmeldung/Abmeldung bis')),
                ('start_date', models.DateTimeField(default=datetime.datetime(2020, 11, 14, 1, 54, 52, 799289), verbose_name='Datum Beginn')),
                ('end_date', models.DateTimeField(default=datetime.datetime(2020, 11, 14, 1, 54, 52, 799289), verbose_name='Datum Ende')),
                ('hinweis', models.CharField(blank=True, max_length=50, verbose_name='Hinweis')),
                ('base_costs', models.IntegerField(blank=True, null=True, verbose_name='Kosten')),
                ('info_only', models.BooleanField(default=False, verbose_name='Nur Ankündigung?')),
                ('teilnahmebedingungen', models.FileField(blank=True, null=True, upload_to='PublicEvents/Docs/', verbose_name='Teilnahmebedingungen')),
                ('datenschutz', models.FileField(blank=True, null=True, upload_to='PublicEvents/Docs/', verbose_name='Datenschutzerklärung')),
                ('einverstaendnis', models.FileField(blank=True, null=True, upload_to='PublicEvents/Docs/', verbose_name='Einverständnis')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='PublicEventParticipantMerch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100, verbose_name='Größe')),
                ('merch', models.ManyToManyField(to='interested.EventMerch')),
                ('participant', models.ManyToManyField(to='interested.EventParticipant')),
            ],
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interested.PublicEvent', verbose_name='Event_ID'),
        ),
    ]
