# Generated by Django 3.0.3 on 2021-04-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interested', '0002_auto_20210423_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicevent',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
