# Generated by Django 3.0.3 on 2021-04-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interested', '0003_auto_20210423_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicevent',
            name='capture',
            field=models.TextField(blank=True, null=True, verbose_name='Kurzbeschreibung'),
        ),
    ]
