# Generated by Django 3.0.3 on 2021-04-23 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interested', '0004_publicevent_capture'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmerch',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interested.PublicEvent', verbose_name='Event'),
        ),
    ]
