# Generated by Django 3.0.3 on 2021-05-10 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interested', '0005_eventmerch_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipant',
            name='invoice',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kosten'),
        ),
    ]
