# Generated by Django 3.0.3 on 2021-05-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interested', '0008_eventparticipant_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicevent',
            name='base_costs',
            field=models.FloatField(blank=True, null=True, verbose_name='Kosten'),
        ),
    ]
