# Generated by Django 3.0.3 on 2021-05-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interested', '0009_auto_20210513_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipant',
            name='invoice',
            field=models.FloatField(blank=True, null=True, verbose_name='Kosten'),
        ),
    ]
