# Generated by Django 3.0.3 on 2022-05-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interested', '0011_auto_20210514_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicevent',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='PublicEvents/Images/Thumbnails', verbose_name='Thumbnail'),
        ),
    ]
