# Generated by Django 3.0.3 on 2022-05-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interested', '0012_publicevent_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicevent',
            name='thumbnail_high',
            field=models.ImageField(blank=True, null=True, upload_to='PublicEvents/Images/Thumbnails', verbose_name='Thumbnail Portrait format'),
        ),
        migrations.AddField(
            model_name='publicevent',
            name='thumbnail_long',
            field=models.ImageField(blank=True, null=True, upload_to='PublicEvents/Images/Thumbnails', verbose_name='Thumbnail Landscape format'),
        ),
        migrations.AlterField(
            model_name='publicevent',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='PublicEvents/Images/Thumbnails', verbose_name='Thumbnail Portrait format'),
        ),
    ]
