# Generated by Django 3.0.3 on 2022-05-27 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interested', '0013_auto_20220527_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicevent',
            name='thumbnail',
        ),
    ]
