# Generated by Django 3.0.3 on 2022-06-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interested', '0014_remove_publicevent_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipant',
            name='contact',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kontaktmöglichkeit'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefonnummer'),
        ),
    ]
