# Generated by Django 3.0.3 on 2022-06-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interested', '0016_auto_20220625_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=300, verbose_name='Nach diesem Schlagwort wird gefiltert (z.B. Twiju)')),
                ('picture', models.ImageField(upload_to='contacts/', verbose_name='Foto')),
                ('name', models.CharField(default='Jon Doe', max_length=100, verbose_name='Name')),
                ('public_telnr', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefonnummer')),
                ('public_email', models.CharField(blank=True, max_length=150, null=True, verbose_name='Email')),
            ],
        ),
    ]
