# Generated by Django 3.0.3 on 2022-08-03 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interested', '0017_contactperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipant',
            name='merch_size',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Größe'),
        ),
    ]
