# Generated by Django 3.0.3 on 2023-03-21 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0043_memberparticipant_storno'),
        ('interested', '0019_tester'),
    ]

    operations = [
        migrations.CreateModel(
            name='TesterBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Batchname')),
                ('unique_ident', models.CharField(blank=True, max_length=300, null=True, verbose_name='Identifier')),
            ],
        ),
        migrations.AddField(
            model_name='tester',
            name='einverstaendnis',
            field=models.FileField(blank=True, null=True, upload_to='Probetrainings/Einverständnis/', verbose_name='Einverständniserklärung'),
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Datum')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interested.TesterBatch')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.Session')),
                ('testers', models.ManyToManyField(blank=True, to='interested.Tester', verbose_name='Anwesende Probetrainingsmenschen')),
            ],
        ),
        migrations.AddField(
            model_name='testerbatch',
            name='testers',
            field=models.ManyToManyField(blank=True, related_name='batch', to='interested.Tester'),
        ),
    ]
