# Generated by Django 3.0.3 on 2023-03-21 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interested', '0020_auto_20230321_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testerbatch',
            name='testers',
        ),
        migrations.AddField(
            model_name='tester',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interested.TesterBatch'),
        ),
    ]
