# Generated by Django 4.2.16 on 2025-03-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interested', '0021_auto_20230321_1016'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactPerson',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='session',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='testers',
        ),
        migrations.RemoveField(
            model_name='tester',
            name='batch',
        ),
        migrations.AlterField(
            model_name='teamer',
            name='city',
            field=models.CharField(blank=True, choices=[('leipzig', 'Leipzig')], max_length=30, verbose_name='Stadt'),
        ),
        migrations.DeleteModel(
            name='TesterBatch',
        ),
        migrations.DeleteModel(
            name='TestSession',
        ),
    ]
