# Generated by Django 4.2.16 on 2026-02-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interested', '0022_delete_contactperson_remove_testsession_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipant',
            name='inform_ok',
            field=models.BooleanField(default=False, verbose_name='Email für Werbung verwenden'),
        ),
    ]
