# Generated by Django 3.0.3 on 2020-12-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0004_auto_20201129_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer_table',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='table_entry',
            name='notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
