# Generated by Django 3.0.3 on 2020-12-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0005_auto_20201211_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table_entry',
            name='session',
        ),
        migrations.AddField(
            model_name='table_entry',
            name='day',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='table_entry',
            name='dur',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='table_entry',
            name='end',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='table_entry',
            name='group',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='table_entry',
            name='start',
            field=models.TextField(blank=True, null=True),
        ),
    ]
