# Generated by Django 3.0.3 on 2020-12-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0006_auto_20201211_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_entry',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
