# Generated by Django 3.0.3 on 2020-12-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0007_auto_20201211_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer_table',
            name='title',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
