# Generated by Django 4.2.16 on 2025-08-24 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0045_alter_chairman_show'),
        ('trainer', '0009_trainer_table_final_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSessionEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('day', models.TextField(blank=True, null=True)),
                ('group', models.TextField(blank=True, null=True)),
                ('start', models.TextField(blank=True, null=True)),
                ('end', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(default='')),
                ('cotrainer', models.ManyToManyField(related_name='cotrainer', to='members.trainer')),
                ('trainer', models.ManyToManyField(related_name='trainer', to='members.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSessionParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notizen')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.trainingsessionentry')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Education',
        ),
    ]
