# Generated by Django 4.2.16 on 2025-08-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0045_alter_chairman_show'),
        ('trainer', '0010_trainingsessionentry_trainingsessionparticipant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsessionentry',
            name='cotrainer',
            field=models.ManyToManyField(blank=True, related_name='cotrainer', to='members.trainer'),
        ),
        migrations.AlterField(
            model_name='trainingsessionentry',
            name='trainer',
            field=models.ManyToManyField(blank=True, related_name='trainer', to='members.trainer'),
        ),
    ]
