# Generated by Django 4.2.16 on 2025-08-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0011_alter_trainingsessionentry_cotrainer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsessionentry',
            name='billed',
            field=models.BooleanField(default=False),
        ),
    ]
