# Generated by Django 4.2.16 on 2025-08-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0012_trainingsessionentry_billed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsessionentry',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
