# Generated by Django 4.2.16 on 2025-10-08 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0013_alter_trainingsessionentry_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsessionentry',
            name='payed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trainingsessionparticipant',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='trainer.trainingsessionentry'),
        ),
    ]
