# Generated by Django 4.2.16 on 2025-12-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0045_alter_chairman_show'),
        ('trainer', '0014_trainingsessionentry_payed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsessionentry',
            name='session',
            field=models.ManyToManyField(blank=True, related_name='session', to='members.session'),
        ),
    ]
