# Generated by Django 4.2.16 on 2025-12-16 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0045_alter_chairman_show'),
        ('trainer', '0015_trainingsessionentry_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingsessionentry',
            name='session',
        ),
        migrations.AddField(
            model_name='trainingsessionentry',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session', to='members.session'),
        ),
    ]
