# Generated by Django 4.2.16 on 2026-02-15 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0047_event_ask_ticket'),
        ('trainer', '0016_remove_trainingsessionentry_session_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSessionInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_billed', models.DateTimeField(blank=True, null=True, verbose_name='Rechnungsdatum')),
                ('date_payed', models.DateTimeField(blank=True, null=True, verbose_name='Bezahldatum')),
                ('total_time', models.FloatField(blank=True, null=True, verbose_name='Stunden')),
                ('total_money', models.FloatField(blank=True, null=True, verbose_name='TAE')),
                ('sessions', models.ManyToManyField(related_name='invoice', to='members.session')),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='members.trainer')),
            ],
        ),
    ]
