# Generated by Django 4.2.16 on 2026-02-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0017_trainingsessioninvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsessioninvoice',
            name='sessions',
            field=models.ManyToManyField(related_name='invoice', to='trainer.trainingsessionentry'),
        ),
    ]
