# Generated by Django 4.2.16 on 2026-02-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0018_alter_trainingsessioninvoice_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsessioninvoice',
            name='invoice_pdf',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='PDF'),
        ),
    ]
