# Generated by Django 3.0.3 on 2020-09-24 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20200904_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 24, 13, 23, 53, 165610), verbose_name='Anmeldung/Abmeldung bis'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 24, 13, 23, 53, 165639), verbose_name='Datum Ende'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 24, 13, 23, 53, 165628), verbose_name='Datum Beginn'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 24, 13, 23, 53, 169347)),
        ),
    ]
