# Generated by Django 3.0.3 on 2020-09-29 01:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20200929_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 29, 3, 37, 54, 772580), verbose_name='Anmeldung/Abmeldung bis'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 29, 3, 37, 54, 772648), verbose_name='Datum Ende'),
        ),
        migrations.AlterField(
            model_name='event',
            name='info_only',
            field=models.BooleanField(default=False, verbose_name='Nur Ankündigung?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 29, 3, 37, 54, 772616), verbose_name='Datum Beginn'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 29, 3, 37, 54, 776821)),
        ),
    ]
