# Generated by Django 3.0.3 on 2020-09-30 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20200929_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='parent',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ansprechpartner*in'),
        ),
        migrations.AddField(
            model_name='profile',
            name='parent_telnr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Notfallnummer'),
        ),
        migrations.AlterField(
            model_name='event',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 12, 39, 36, 504055), verbose_name='Anmeldung/Abmeldung bis'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 12, 39, 36, 504087), verbose_name='Datum Ende'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 12, 39, 36, 504075), verbose_name='Datum Beginn'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 12, 39, 36, 510110)),
        ),
    ]
