# Generated by Django 3.0.3 on 2020-04-24 20:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0009_auto_20200424_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='titel',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='groups',
        ),
        migrations.AddField(
            model_name='group',
            name='trainer',
            field=models.ManyToManyField(to='members.Trainer'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 24, 22, 44, 14, 421495)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 24, 22, 44, 14, 421473)),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2020, 4, 24, 22, 44, 14, 421030)),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2020, 4, 24, 22, 44, 14, 421003)),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('message', models.TextField(default='Deine Nachricht hier')),
                ('expire_date', models.DateTimeField(default=datetime.datetime(2020, 4, 24, 22, 44, 14, 421844))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('display', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Session')),
            ],
        ),
    ]
