# Generated by Django 3.0.3 on 2020-04-24 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_auto_20200424_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 24, 23, 16, 26, 629838)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 24, 23, 16, 26, 629822)),
        ),
        migrations.AlterField(
            model_name='message',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 24, 23, 16, 26, 630200)),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2020, 4, 24, 23, 16, 26, 629472)),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2020, 4, 24, 23, 16, 26, 629446)),
        ),
    ]
