# Generated by Django 3.0.3 on 2020-04-25 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_auto_20200424_2357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['day']},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='telnr',
        ),
        migrations.AddField(
            model_name='spot',
            name='adress',
            field=models.TextField(blank=True, verbose_name='Adresse/Wegbeschreibung'),
        ),
        migrations.AddField(
            model_name='spot',
            name='picture',
            field=models.ImageField(default='spot_placeholder.jpg', upload_to='spot_pics/', verbose_name='Foto vom Spot'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics/', verbose_name='Profilbild'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 25, 17, 19, 23, 407500), verbose_name='Datum Ende'),
        ),
        migrations.AlterField(
            model_name='event',
            name='hinweis',
            field=models.CharField(blank=True, max_length=50, verbose_name='Hinweis (rote Anzeige)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 25, 17, 19, 23, 407483), verbose_name='Datum Beginn'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Event-name'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_id',
            field=models.CharField(max_length=10, verbose_name='Gruppenname'),
        ),
        migrations.AlterField(
            model_name='message',
            name='display',
            field=models.CharField(choices=[('sessions', 'Sessions'), ('events', 'Events')], max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 25, 17, 19, 23, 407866)),
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='member_num',
            field=models.CharField(blank=True, max_length=30, verbose_name='Mitgliedsnummer'),
        ),
        migrations.AlterField(
            model_name='session',
            name='day',
            field=models.CharField(default='Mo', max_length=2, verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2020, 4, 25, 17, 19, 23, 407005), verbose_name='Ende'),
        ),
        migrations.AlterField(
            model_name='session',
            name='hinweis',
            field=models.CharField(blank=True, max_length=50, verbose_name='Hinweise (rote Anzeige)'),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2020, 4, 25, 17, 19, 23, 406982), verbose_name='Beginn'),
        ),
        migrations.AlterField(
            model_name='session',
            name='title',
            field=models.CharField(default='Halle_GruppeA_Sa', max_length=50, verbose_name='Titel für uns'),
        ),
        migrations.AlterField(
            model_name='session',
            name='website_title',
            field=models.CharField(default='Hallentraining', max_length=50, verbose_name='Titel für Website'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='coords',
            field=models.CharField(max_length=100, verbose_name='Coordinaten'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Spotname'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='trainer_email',
            field=models.CharField(default='Hier die Email für die Website', max_length=150, verbose_name='Öffentliche Email'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='trainer_telnr',
            field=models.CharField(default='Hier die Nummer für die Website', max_length=100, verbose_name='Öffentliche Telefonnummer'),
        ),
    ]
