# Generated by Django 3.0.3 on 2020-11-14 00:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_auto_20201108_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 14, 1, 54, 52, 799289), verbose_name='Anmeldung/Abmeldung bis'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 14, 1, 54, 52, 799344), verbose_name='Datum Ende'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 14, 1, 54, 52, 799331), verbose_name='Datum Beginn'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 14, 1, 54, 52, 803044)),
        ),
        migrations.AlterField(
            model_name='spot',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='spot_pics/', verbose_name='Foto vom Spot'),
        ),
    ]
