# Generated by Django 3.0.3 on 2020-04-26 14:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0014_auto_20200426_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 16, 35, 45, 976725), verbose_name='Datum Ende'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 16, 35, 45, 976706), verbose_name='Datum Beginn'),
        ),
        migrations.AlterField(
            model_name='message',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 16, 35, 45, 977081)),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2020, 4, 26, 16, 35, 45, 976064), verbose_name='Ende'),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2020, 4, 26, 16, 35, 45, 976041), verbose_name='Beginn'),
        ),
        migrations.CreateModel(
            name='Chairman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_telnr', models.CharField(default='Hier die Nummer für die Website', max_length=100, verbose_name='Öffentliche Telefonnummer')),
                ('trainer_email', models.CharField(default='Hier die Email für die Website', max_length=150, verbose_name='Öffentliche Email')),
                ('competences', models.TextField(verbose_name='Zuständigkeiten')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics/', verbose_name='Profilbild')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
