# Generated by Django 3.0.3 on 2020-04-26 19:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0015_auto_20200426_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chairman',
            old_name='trainer_email',
            new_name='public_email',
        ),
        migrations.RenameField(
            model_name='chairman',
            old_name='trainer_telnr',
            new_name='public_telnr',
        ),
        migrations.RemoveField(
            model_name='group',
            name='group_events',
        ),
        migrations.RemoveField(
            model_name='group',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='group',
            name='trainer',
        ),
        migrations.AddField(
            model_name='event',
            name='allowed_groups',
            field=models.ManyToManyField(to='members.Group'),
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='session',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Group'),
        ),
        migrations.AddField(
            model_name='session',
            name='trainer',
            field=models.ManyToManyField(to='members.Trainer'),
        ),
        migrations.AlterField(
            model_name='chairman',
            name='competences',
            field=models.TextField(verbose_name='Zuständigkeiten (mit Komma getrennt)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 21, 36, 27, 897477), verbose_name='Datum Ende'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 21, 36, 27, 897452), verbose_name='Datum Beginn'),
        ),
        migrations.AlterField(
            model_name='message',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 21, 36, 27, 900473)),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2020, 4, 26, 21, 36, 27, 899481), verbose_name='Ende'),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2020, 4, 26, 21, 36, 27, 899465), verbose_name='Beginn'),
        ),
    ]
