# Generated by Django 3.0.3 on 2020-11-26 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_auto_20201122_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='license',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lizenznummer'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='license_valid',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 14, 1, 54, 52, 799289), null=True, verbose_name='Gültigkeit'),
        ),
    ]
