# Generated by Django 3.0.3 on 2020-11-26 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_trainer_license_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='codex',
            field=models.FileField(blank=True, null=True, upload_to='trainer_stuff', verbose_name='Ehrencodex'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='contract',
            field=models.FileField(blank=True, null=True, upload_to='trainer_stuff', verbose_name='Vertrag'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lizenznummer'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='salary',
            field=models.FloatField(blank=True, null=True, verbose_name='Bezahlung'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='license',
            field=models.FileField(blank=True, null=True, upload_to='trainer_stuff', verbose_name='Lizenz'),
        ),
    ]
