# Generated by Django 3.0.3 on 2020-11-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_auto_20201126_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='license_valid',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Gültigkeit'),
        ),
    ]
