# Generated by Django 3.0.3 on 2020-04-29 22:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_auto_20200429_0103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainer',
            options={'permissions': (('can_add_event', 'Can add an event'), ('can_change_event', 'Can change an event'), ('can_delete_event', 'can delete an event'), ('can_add_session', 'Can add a Session'), ('can_change_session', 'Can change a Session'), ('can_delete_session', 'Can delete a Session'))},
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 30, 0, 40, 53, 56361), verbose_name='Datum Ende'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 30, 0, 40, 53, 56341), verbose_name='Datum Beginn'),
        ),
        migrations.AlterField(
            model_name='message',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 30, 0, 40, 53, 59421)),
        ),
    ]
