# Generated by Django 3.0.3 on 2020-11-27 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_auto_20201126_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='salary',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Bezahlung'),
        ),
    ]
