# Generated by Django 3.0.3 on 2020-04-30 00:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_auto_20200430_0040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainer',
            options={},
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.CharField(blank=True, default='Leipzig', max_length=200, verbose_name='Veranstaltungsort'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 30, 2, 35, 8, 194208), verbose_name='Datum Ende'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 30, 2, 35, 8, 194185), verbose_name='Datum Beginn'),
        ),
        migrations.AlterField(
            model_name='message',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 30, 2, 35, 8, 196919)),
        ),
    ]
