# Generated by Django 3.0.3 on 2020-04-30 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_auto_20200430_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 30, 13, 9, 4, 907913), verbose_name='Anmeldung/Abmeldung bis'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 30, 13, 9, 4, 907943), verbose_name='Datum Ende'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 30, 13, 9, 4, 907933), verbose_name='Datum Beginn'),
        ),
        migrations.AlterField(
            model_name='message',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 30, 13, 9, 4, 910902)),
        ),
    ]
