# Generated by Django 3.0.3 on 2021-11-29 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_auto_20210423_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chairman',
            name='public_email',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Öffentliche Email'),
        ),
        migrations.AlterField(
            model_name='chairman',
            name='public_telnr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Öffentliche Telefonnummer'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(blank=True, default='Deine Nachricht hier', null=True, verbose_name='Hinweis'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='trainer_email',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Öffentliche Email'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='trainer_telnr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Öffentliche Telefonnummer'),
        ),
    ]
