# Generated by Django 3.0.3 on 2021-12-05 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0022_auto_20211129_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Titel')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='Emailadresse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
