# Generated by Django 3.0.3 on 2021-12-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_additionalemail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['member_num']},
        ),
        migrations.AlterField(
            model_name='profile',
            name='member_num',
            field=models.IntegerField(blank=True, verbose_name='Mitgliedsnummer'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(max_length=1, verbose_name='Geschlecht'),
        ),
    ]
