# Generated by Django 3.0.3 on 2022-01-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0024_auto_20211230_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='member_num',
            field=models.CharField(blank=True, max_length=30, verbose_name='Mitgliedsnummer'),
        ),
    ]
