# Generated by Django 3.0.3 on 2022-03-15 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0025_auto_20220104_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='galleries/', verbose_name='Image')),
                ('alt', models.TextField(blank=True, null=True, verbose_name='Alt text')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Gallery')),
            ],
        ),
    ]
