# Generated by Django 3.0.3 on 2022-03-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0029_shopitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='price',
            field=models.FloatField(blank=True, verbose_name='Price'),
        ),
    ]
