# Generated by Django 3.0.3 on 2022-03-16 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0031_auto_20220315_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='priority',
            field=models.IntegerField(default=1, verbose_name='Priority'),
            preserve_default=False,
        ),
    ]
