# Generated by Django 3.0.3 on 2022-03-20 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0032_image_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='visible',
            field=models.BooleanField(default='True', verbose_name='Visible'),
        ),
    ]
