# Generated by Django 3.0.3 on 2022-03-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0033_shopitem_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='priority',
            field=models.IntegerField(default=99, verbose_name='Priority'),
        ),
    ]
