# Generated by Django 3.0.3 on 2022-03-24 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0034_shopitem_priority'),
        ('members', '0027_auto_20220320_1852'),
    ]

    operations = [
    ]
