# Generated by Django 3.0.3 on 2023-01-07 19:33

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0036_auto_20220527_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower', models.IntegerField(default=0, verbose_name='von')),
                ('upper', models.IntegerField(default=99, verbose_name='bis')),
            ],
        ),
        migrations.AlterField(
            model_name='chairman',
            name='show',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('member_site', 'Anzeige Mitglieder'), ('interested_site', 'Anzeige Interessierte'), ('event_site', 'Anzeige Veranstalter')], max_length=300),
        ),
    ]
