# Generated by Django 3.0.3 on 2023-01-08 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0038_session_agegroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agegroup',
            options={'ordering': ['lower']},
        ),
        migrations.AddField(
            model_name='event',
            name='allowed_agegroups',
            field=models.ManyToManyField(blank=True, related_name='event', to='members.AgeGroup', verbose_name='Altersgruppen'),
        ),
        migrations.AlterField(
            model_name='event',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, to='members.Group', verbose_name='Für die Gruppen'),
        ),
    ]
