# Generated by Django 3.0.3 on 2023-01-08 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0039_auto_20230108_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='agegroup',
            field=models.ManyToManyField(blank=True, related_name='message', to='members.AgeGroup', verbose_name='Altersgruppen'),
        ),
        migrations.AlterField(
            model_name='message',
            name='groups',
            field=models.ManyToManyField(blank=True, to='members.Group', verbose_name='Für die Gruppen'),
        ),
    ]
