# Generated by Django 3.0.3 on 2023-02-26 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0041_message_autodelete'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='visible',
            field=models.BooleanField(default=False, verbose_name='Visible'),
        ),
    ]
