# Generated by Django 3.0.3 on 2023-05-11 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0043_memberparticipant_storno'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberparticipant',
            name='has_ticket',
            field=models.BooleanField(default=False, verbose_name='Deutschlandticket'),
        ),
    ]
