# Generated by Django 3.0.3 on 2024-03-10 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0044_memberparticipant_has_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='allowed_agegroups',
        ),
        migrations.RemoveField(
            model_name='event',
            name='allowed_groups',
        ),
        migrations.AddField(
            model_name='event',
            name='short',
            field=models.TextField(blank=True, null=True, verbose_name='Kurzbeschreibung'),
        ),
    ]
