# Generated by Django 3.0.3 on 2024-03-10 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0045_auto_20240310_0253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='participants',
        ),
        migrations.AddField(
            model_name='event',
            name='max_age',
            field=models.IntegerField(default=99, verbose_name='Höchstalter'),
        ),
        migrations.AddField(
            model_name='event',
            name='min_age',
            field=models.IntegerField(default=0, verbose_name='Mindestalter'),
        ),
        migrations.AlterField(
            model_name='memberparticipant',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='members.Event'),
        ),
    ]
