# Generated by Django 4.2.16 on 2025-12-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0045_alter_chairman_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='session', to='members.profile'),
        ),
    ]
