# Generated by Django 4.2.16 on 2025-01-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0045_alter_chairman_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='data',
            field=models.JSONField(blank=True, null=True, verbose_name='data'),
        ),
        migrations.AddField(
            model_name='news',
            name='intern',
            field=models.BooleanField(default=True, verbose_name='Intern'),
        ),
        migrations.AddField(
            model_name='news',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Öffentlich'),
        ),
    ]
