# Generated by Django 3.0.3 on 2024-03-10 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0046_auto_20240310_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='description_rendered',
        ),
    ]
