# Generated by Django 4.2.16 on 2026-02-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0046_session_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ask_ticket',
            field=models.BooleanField(default=False, verbose_name='Deutschlandticket Abfragen'),
        ),
    ]
