# Generated by Django 3.0.3 on 2024-03-10 14:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0047_auto_20240310_1418'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MemberParticipant',
            new_name='Participant',
        ),
    ]
