# Generated by Django 3.0.3 on 2024-03-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0049_auto_20240310_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fields',
            field=models.TextField(blank=True, null=True, verbose_name='Formfelder'),
        ),
    ]
