# Generated by Django 3.0.3 on 2024-03-10 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0052_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='description', to='members.Event'),
        ),
    ]
