# Generated by Django 3.0.3 on 2024-03-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0053_auto_20240310_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='description_images/', verbose_name='Foto')),
            ],
        ),
    ]
