# Generated by Django 3.0.3 on 2024-03-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0054_descriptionimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='external_costs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Externe Kosten'),
        ),
    ]
