# Generated by Django 3.0.3 on 2024-03-10 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0055_event_external_costs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='agegroup',
        ),
        migrations.RemoveField(
            model_name='message',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='group',
        ),
        migrations.RemoveField(
            model_name='session',
            name='agegroup',
        ),
        migrations.RemoveField(
            model_name='session',
            name='group',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='description',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='description_rendered',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='picture',
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AgeGroup',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
