# Generated by Django 3.0.3 on 2024-03-13 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0057_auto_20240311_0058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='fields',
            new_name='questions',
        ),
    ]
