# Generated by Django 3.0.3 on 2024-03-13 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0058_auto_20240313_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='fields',
            new_name='answers',
        ),
    ]
