# Generated by Django 3.0.3 on 2024-03-15 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0059_auto_20240313_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='permission_level',
            field=models.IntegerField(default=0, verbose_name='Permission Level'),
        ),
    ]
