# Generated by Django 3.0.3 on 2024-03-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0061_event_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='costs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Kosten für Mitglieder'),
        ),
        migrations.AlterField(
            model_name='event',
            name='einverstaendnis',
            field=models.FileField(blank=True, null=True, upload_to='Events/Docs/', verbose_name='Einverständniserklärung'),
        ),
        migrations.AlterField(
            model_name='event',
            name='external_costs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Kosten für Nichtmitglieder'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Eventname'),
        ),
    ]
