# Generated by Django 3.0.3 on 2024-03-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0063_auto_20240315_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Geburtstag'),
        ),
        migrations.AddField(
            model_name='participant',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Emailadresse'),
        ),
        migrations.AddField(
            model_name='participant',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Vorname'),
        ),
        migrations.AddField(
            model_name='participant',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nachname'),
        ),
        migrations.AddField(
            model_name='participant',
            name='sex',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Geschlecht'),
        ),
        migrations.AddField(
            model_name='participant',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telephone'),
        ),
    ]
