# Generated by Django 3.0.3 on 2024-03-19 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0065_auto_20240315_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='trainer_only',
            field=models.BooleanField(default=False, verbose_name='Nur für Trainer'),
        ),
    ]
