# Generated by Django 3.0.3 on 2024-03-23 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0066_event_trainer_only'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['start_time']},
        ),
        migrations.RemoveField(
            model_name='session',
            name='day_key',
        ),
        migrations.AddField(
            model_name='session',
            name='max_age',
            field=models.IntegerField(default=99, verbose_name='Höchstalter'),
        ),
        migrations.AddField(
            model_name='session',
            name='min_age',
            field=models.IntegerField(default=0, verbose_name='Mindestalter'),
        ),
        migrations.AlterField(
            model_name='session',
            name='spot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session', to='members.Spot', verbose_name='Spot'),
        ),
        migrations.AlterField(
            model_name='session',
            name='trainer',
            field=models.ManyToManyField(blank=True, related_name='session', to='members.Trainer', verbose_name='Trainer'),
        ),
    ]
