# Generated by Django 3.0.3 on 2024-03-23 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0067_auto_20240323_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={},
        ),
    ]
