# Generated by Django 3.0.3 on 2024-03-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0069_session_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='outdoor',
            field=models.BooleanField(default=True, verbose_name='Outdoor'),
        ),
    ]
