# Generated by Django 3.0.3 on 2024-03-23 20:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0070_spot_outdoor'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='session', to=settings.AUTH_USER_MODEL),
        ),
    ]
