# Generated by Django 3.2.8 on 2024-03-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0071_session_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Vorname')),
                ('last_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nachname')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='Emailadresse')),
                ('sex', models.CharField(blank=True, max_length=200, null=True, verbose_name='Geschlecht')),
                ('birthday', models.DateTimeField(blank=True, null=True, verbose_name='Geburtstag')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telephone')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Anmerkungen')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
