# Generated by Django 3.2.8 on 2024-03-26 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0072_tester'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Namen')),
                ('tester', models.ManyToManyField(related_name='batch', to='members.Tester')),
            ],
        ),
    ]
