# Generated by Django 3.2.8 on 2024-03-26 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0073_trialbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='tester',
            name='progress',
            field=models.TextField(default="{'Antwort':'0'}", verbose_name='Workflow'),
        ),
    ]
