# Generated by Django 3.2.8 on 2024-03-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0074_tester_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='tester',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Anfragedatum'),
        ),
    ]
