# Generated by Django 3.2.8 on 2024-04-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0075_tester_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='display',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Hinweis'),
        ),
    ]
