# Generated by Django 3.0.3 on 2024-07-24 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0078_auto_20240722_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spot',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='session',
            name='spot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='session', to='members.Spot', verbose_name='Spot'),
        ),
    ]
